Repository aCupOfHotJava/Ethics_Dashboard_1, pull requests merged in 2021-11, with the labels that each got.

#73 Care ethics
  Project/styles/main.css
Labels: task, chore

#76 login, creation finished for local database, basic session state
  Project/html/create-account.html
  Project/html/login.html
  Project/server/createAccount.php
  Project/server/logout.php
  Project/server/processLogin.php
Labels: task

#82 Deontology
  Project/html/Deontology/Deontology1.html
  Project/html/Deontology/Deontology2.html
  Project/html/Deontology/Deontology3.html
  Project/html/index.html
  Project/scripts/user-event.js
Labels: task

#86 Deontology pages all added
  Project/html/Deontology/Deontology1.html
  Project/html/Deontology/Deontology2.html
  Project/html/Deontology/Deontology4.html
  Project/html/Deontology/Deontology5.html
  Project/html/Deontology/Deontology6.html
  Project/html/Deontology/Deontology7.html
  Project/html/Deontology/Deontology8.html
Labels: chore

#93 Fixed nav panels across all pages, added some better styling, etc
  Project/html/CareEthics/CareEthicOption2.html
  Project/html/CareEthics/CareEthics.html
  Project/html/CareEthics/CareEthicsOptions3.html
  Project/html/Deontology/Deontology1.html
  Project/html/Deontology/Deontology2.html
  Project/html/Deontology/Deontology4.html
  Project/html/Deontology/Deontology5.html
  Project/html/Deontology/Deontology6.html
  Project/html/Deontology/Deontology7.html
  Project/html/Deontology/Deontology8.html
  Project/html/MyProgress.html
  Project/html/Utilitarianism/utilitarianism-analysis/utilitarianism-analysis1.html
  Project/html/Utilitarianism/utilitarianism-analysis/utilitarianism-analysis2.html
  Project/html/Utilitarianism/utilitarianism-analysis/utilitarianism-analysis3.html
  Project/html/Utilitarianism/utilitarianism-analysis/utilitarianism-analysis4.html
  Project/html/Utilitarianism/utilitarianism-stakeholders.html
  Project/html/Utilitarianism/utilitarianism-summary.html
  Project/html/Utilitarianism/utilitarianism.html
  Project/html/VirtueEthics/VirtueEthics-options.html
  Project/html/VirtueEthics/VirtueEthics1.html
  Project/html/VirtueEthics/VirtueEthics2.html
  Project/html/VirtueEthics/VirtueEthics3.html
  Project/html/VirtueEthics/VirtueEthics4.html
  Project/html/ethical-issues.html
  Project/html/index.html
  Project/html/stakeholder-analysis.html
  Project/html/stakeholders-main.html
Labels: task

#98 session state implemented across all pages
  Project/html/CareEthics/CareEthicOption2.php
  Project/html/CareEthics/CareEthics.php
  Project/html/CareEthics/CareEthicsOptions3.php
  Project/html/Deontology/Deontology1.php
  Project/html/Deontology/Deontology2.php
  Project/html/Deontology/Deontology4.php
  Project/html/Deontology/Deontology5.php
  Project/html/Deontology/Deontology6.php
  Project/html/Deontology/Deontology7.php
  Project/html/Deontology/Deontology8.php
  Project/html/MyProgress.php
  Project/html/Utilitarianism/utilitarianism-analysis/utilitarianism-analysis1.php
  Project/html/Utilitarianism/utilitarianism-analysis/utilitarianism-analysis2.php
  Project/html/Utilitarianism/utilitarianism-analysis/utilitarianism-analysis3.php
  Project/html/Utilitarianism/utilitarianism-analysis/utilitarianism-analysis4.php
  Project/html/Utilitarianism/utilitarianism-stakeholders.php
  Project/html/Utilitarianism/utilitarianism-summary.php
  Project/html/Utilitarianism/utilitarianism.php
  Project/html/VirtueEthics/VirtueEthics-options.php
  Project/html/VirtueEthics/VirtueEthics1.php
  Project/html/VirtueEthics/VirtueEthics2.php
  Project/html/VirtueEthics/VirtueEthics3.php
  Project/html/VirtueEthics/VirtueEthics4.php
  Project/html/create-account.php
  Project/html/ethical-issues.php
  Project/html/index.php
  Project/html/login.php
  Project/html/stakeholder-analysis.php
  Project/html/stakeholders-main.php
  Project/server/createAccount.php
  Project/server/logout.php
  Project/server/processLogin.php
  Project/server/utilitarianismOptions.php
  Project/server/virtueEthics-options.php
Labels: task
